version: '2'

services:
    db:
        image: mysql:5
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        restart: always
        container_name: symfony-db

    symfony:
        build: 
            context: symfony-project
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./symfony-project:/var/www/html
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DB_NAME: ${MYSQL_DB_NAME}
            SYMFONY_APP_ENV: "dev"
            DATABASE_URL: "mysql://root:${MYSQL_ROOT_PASSWORD}@db:3306/${MYSQL_DB_NAME}"
        ports:
            - '8088:80'
        restart: always
        container_name: symfony-project
